### ISSUE TITLE
Kernel crashes when changing object orientation

### ISSUE THREAD

**Issue by robpegurri** [NVlabs/sionna#633]
Hello everyone, I'm having some headaches trying to change the orientation of an object to any value: the kernel always crashes.

All I'm doing is simply setting: `object.orientation = [new_angle*np.pi/180, 0, 0]`. The same happens if, just for testing, I put `[0, 0, 0]`.

<img width="1077" alt="Screenshot 2024-10-29 at 00 00 10" src="https://github.com/user-attachments/assets/153c9edf-7d00-4091-a4f4-cc71ab57a521">

All I can see from terminal is:
`Critical Dr.Jit compiler failure: jit_var(r0): unknown variable!
Aborted (core dumped)`

I really can't understand what's wrong here, the .position is working flawlessly.
Has anybody any idea? Thanks!

**Comment by Leeyyhh** [comment]
Hi, I am facing the same issue. When I change the orientation, I receive the error message: 'The kernel appears to have died. It will restart automatically.' Have you found a solution to this problem?

**Comment by merlinND** [comment]
Hello @robpegurri and @Leeyyhh,

Could you please try the following and let us know if it solves the crash?

```py
new_orientation = (np.pi, 0,  0)
obj.orientation = type(obj.orientation)(new_orientation)
```

**Comment by Leeyyhh** [comment]
@merlinND 
Thank you for your answer！ However, the program reports an error, as shown in the image below:
 
<img width="947" alt="Weixin Image_20241123202339" src="https://github.com/user-attachments/assets/3ce75970-8a90-4f5b-9858-0c1ea3391d26">
 

PS: For those who may need an urgent solution, I found a method to address this. We can modify the target object's orientation by editing the target_object.ply file using the plyfile package in Python, and then reload the XML file. This will result in a rotated object. However, a limitation of this method is that the rotation information cannot be accessed through target_object.orientation.numpy(). We can save the roration information manually.

**Comment by merlinND** [comment]
According to the error message, you need to specify the device for the tensor as well:

```py
cuboid.orientation = type(cuboid.orientation)(new_orientation, device=cuboid.orientation.device)
```

Which version of Sionna are you using? I remember reports of a similar crash, but it has been fixed a while ago.

**Comment by robpegurri** [comment]
Unfortunately in my case, using:

`new_orientation = (new_angle*np.pi/180, 0, 0)
 from_sionna.orientation = type(from_sionna.orientation)(new_orientation, device=from_sionna.orientation.device)
`
``
where new_angle is in degrees, still crashes the kernel. Same thing happens by using any radians value.

**Comment by merlinND** [comment]
@robpegurri Are you using the latest version of Sionna and its dependencies? (you can try a clean `pip install sionna` in a new virtual environment to get the latest compatible versions of the dependencies).

If it still crashes with the latest version, could you please paste the full stack trace / error message shown when the kernel crashes.

**Comment by MOX233** [comment]
@merlinND Hello, I'm also struggling with this problem. I use the latest version of Sionna, but when I run the following codes:
`new_orientation = (np.pi, 0,  0)
car.orientation = type(car.orientation)(new_orientation, device=car.orientation.device)`
the program will also have the error "Critical Dr.Jit compiler failure: jit_var(r0): unknown variable! Aborted (core dumped)".
Is there any other way to fix this error?

**Comment by merlinND** [comment]
Hello @MOX233,

Do you still encounter this issue with the new release (1.0.1)? If so, could you please open a new issue with all details.
